"""add store code column

Revision ID: 07de3cbbbd0d
Revises: 692422e75990
Create Date: 2026-03-25 11:00:32.787778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07de3cbbbd0d'
down_revision: Union[str, None] = '692422e75990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'code')
    # ### end Alembic commands ###
