"""add warnings table

Revision ID: 08df66aeb81c
Revises: 5f81cc7fde3c
Create Date: 2026-06-09 13:55:58.192412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08df66aeb81c'
down_revision: Union[str, None] = '5f81cc7fde3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warnings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('issued_by_id', sa.Uuid(), nullable=True),
    sa.Column('subject_user_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('categories', postgresql.ARRAY(sa.String(length=40)), server_default='{}', nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('warning_date', sa.Date(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'seq', name='uq_warning_org_seq')
    )
    op.create_index('ix_warnings_org_deleted', 'warnings', ['organization_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_warnings_organization_id'), 'warnings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_warnings_subject_user_id'), 'warnings', ['subject_user_id'], unique=False)
    # NOTE: autogenerate 가 함께 잡은 무관한 legacy 드리프트(notifications/announcements
    # drop, alerts/notices/reports/tasks 인덱스, users.notification_preferences 등)는
    # 의도적으로 제거했다. 이 마이그레이션은 warnings 테이블만 추가한다.


def downgrade() -> None:
    op.drop_index(op.f('ix_warnings_subject_user_id'), table_name='warnings')
    op.drop_index(op.f('ix_warnings_organization_id'), table_name='warnings')
    op.drop_index('ix_warnings_org_deleted', table_name='warnings')
    op.drop_table('warnings')
