"""add min_photos to checklist_template_items

Revision ID: 0f8f46005818
Revises: d3b13f52b56c
Create Date: 2026-03-26 11:34:48.230177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8f46005818'
down_revision: Union[str, None] = 'd3b13f52b56c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_template_items', sa.Column('min_photos', sa.Integer(), server_default='1', nullable=False))
    # photo가 아닌 항목은 min_photos=0
    op.execute(sa.text("""
        UPDATE checklist_template_items
        SET min_photos = 0
        WHERE verification_type NOT LIKE '%photo%'
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_template_items', 'min_photos')
    # ### end Alembic commands ###
