"""drop schedule_periods table

Revision ID: 15693302b4e1
Revises: a53c82dcc86c
Create Date: 2026-04-07 14:17:13.355551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15693302b4e1'
down_revision: Union[str, None] = 'a53c82dcc86c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schedule_periods_dates', table_name='schedule_periods')
    op.drop_index('ix_schedule_periods_org_store', table_name='schedule_periods')
    op.drop_table('schedule_periods')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_periods',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('request_deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='schedule_periods_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='schedule_periods_organization_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='schedule_periods_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='schedule_periods_pkey')
    )
    op.create_index('ix_schedule_periods_org_store', 'schedule_periods', ['organization_id', 'store_id'], unique=False)
    op.create_index('ix_schedule_periods_dates', 'schedule_periods', ['store_id', 'period_start', 'period_end'], unique=False)
    # ### end Alembic commands ###
