"""org_member leave fields (D5)

Revision ID: 1d3a46e5711b
Revises: 6bf15e14f25a
Create Date: 2026-08-13 23:51:32.612943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3a46e5711b'
down_revision: Union[str, None] = '6bf15e14f25a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_members', sa.Column('leave_start_date', sa.Date(), nullable=True))
    op.add_column('org_members', sa.Column('leave_end_date', sa.Date(), nullable=True))
    op.add_column('org_members', sa.Column('leave_type', sa.String(length=50), nullable=True))
    op.add_column('org_members', sa.Column('leave_is_paid', sa.Boolean(), nullable=True))
    op.add_column('org_members', sa.Column('leave_note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_members', 'leave_note')
    op.drop_column('org_members', 'leave_is_paid')
    op.drop_column('org_members', 'leave_type')
    op.drop_column('org_members', 'leave_end_date')
    op.drop_column('org_members', 'leave_start_date')
    # ### end Alembic commands ###
