"""eager_attendance_split_shifts

Revision ID: 21c1e7c7afd2
Revises: 782b62157709
Create Date: 2026-04-24 14:19:18.211277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21c1e7c7afd2'
down_revision: Union[str, None] = '782b62157709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── Schema: drop old user+date unique, add partial unique indexes ──
    op.drop_constraint('uq_attendance_user_date', 'attendances', type_='unique')
    op.create_index(
        'uq_attendance_schedule',
        'attendances',
        ['schedule_id'],
        unique=True,
        postgresql_where=sa.text('schedule_id IS NOT NULL'),
    )
    op.create_index(
        'uq_attendance_walkin',
        'attendances',
        ['user_id', 'work_date'],
        unique=True,
        postgresql_where=sa.text('schedule_id IS NULL'),
    )

    # ── Data: not_yet → upcoming (enum rename) ──
    op.execute("UPDATE attendances SET status = 'upcoming' WHERE status = 'not_yet'")

    # ── Data: backfill attendance rows for schedules that currently have none ──
    # confirmed 중 end_time 이미 지났으면 no_show, 시작 지났으면 late, 그 전이면 upcoming.
    # cancelled/rejected schedule 은 attendance row 없이 두는 게 나음 (이후 service 훅에서 생성시 cancelled 로 표기).
    # draft/requested 는 upcoming 으로.
    op.execute(
        """
        INSERT INTO attendances (
            id, organization_id, store_id, user_id, schedule_id, work_date,
            status, created_at, updated_at
        )
        SELECT
            gen_random_uuid(),
            s.organization_id,
            s.store_id,
            s.user_id,
            s.id,
            s.work_date,
            CASE
                WHEN s.status IN ('cancelled', 'rejected', 'deleted') THEN 'cancelled'
                WHEN s.end_time IS NOT NULL
                     AND (s.work_date + s.end_time) AT TIME ZONE COALESCE(st.timezone, 'UTC') < now()
                     THEN 'no_show'
                WHEN s.start_time IS NOT NULL
                     AND (s.work_date + s.start_time) AT TIME ZONE COALESCE(st.timezone, 'UTC')
                          + INTERVAL '5 minutes' < now()
                     THEN 'late'
                ELSE 'upcoming'
            END AS status,
            now(),
            now()
        FROM schedules s
        LEFT JOIN stores st ON st.id = s.store_id
        LEFT JOIN attendances a ON a.schedule_id = s.id
        WHERE a.id IS NULL
          AND s.user_id IS NOT NULL
          AND s.store_id IS NOT NULL
          AND s.organization_id IS NOT NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_attendance_walkin', table_name='attendances', postgresql_where=sa.text('schedule_id IS NULL'))
    op.drop_index('uq_attendance_schedule', table_name='attendances', postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.create_unique_constraint('uq_attendance_user_date', 'attendances', ['user_id', 'work_date'])
    # ### end Alembic commands ###
