"""add applications.rejected_at

Revision ID: 22390ed69baa
Revises: a7c1e9d40b52
Create Date: 2026-08-13 12:55:30.298526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22390ed69baa'
down_revision: Union[str, None] = 'a7c1e9d40b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # 기존 rejected/withdrawn 행 백필 — 정확한 거절 시각 기록이 없으므로 updated_at 으로.
    # (Pipeline 의 "최근 7일" 필터가 과거 데이터에서도 그럴듯하게 동작하게 하기 위함)
    op.execute(
        "UPDATE applications SET rejected_at = updated_at "
        "WHERE stage IN ('rejected', 'withdrawn') AND rejected_at IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'rejected_at')
    # ### end Alembic commands ###
