"""add contacts tables

Revision ID: 2634e2879617
Revises: a4820892e35f
Create Date: 2026-08-14 21:47:18.826464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2634e2879617'
down_revision: Union[str, None] = '627a32cf25db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('change_request_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_audit_contact', 'contact_audit_log', ['contact_id', 'created_at'], unique=False)
    op.create_index('ix_contact_audit_org_created', 'contact_audit_log', ['organization_id', 'created_at'], unique=False)
    op.create_table('contact_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_contact_tags_org_key')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contacts_org_deleted', 'contacts', ['organization_id', 'deleted_at'], unique=False)
    op.create_index('ix_contacts_org_name_lower', 'contacts', ['organization_id', sa.text('lower(name)')], unique=False)
    op.create_index('ix_contacts_org_store', 'contacts', ['organization_id', 'store_id'], unique=False)
    op.create_table('contact_change_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('request_type', sa.String(length=10), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.Column('contact_name_snapshot', sa.String(length=200), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('applied_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='pending', nullable=False),
    sa.Column('base_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('requested_by_name', sa.String(length=200), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_by_name', sa.String(length=200), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ccr_contact', 'contact_change_requests', ['contact_id', 'status'], unique=False)
    op.create_index('ix_ccr_org_status', 'contact_change_requests', ['organization_id', 'status', 'requested_at'], unique=False)
    op.create_index('ix_ccr_requester', 'contact_change_requests', ['requested_by', 'requested_at'], unique=False)
    op.create_table('contact_phones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('number_normalized', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_phones_contact', 'contact_phones', ['contact_id', 'sort_order'], unique=False)
    op.create_index('ix_contact_phones_normalized', 'contact_phones', ['number_normalized'], unique=False)
    op.create_table('contact_tag_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['contact_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'tag_id', name='uq_contact_tag_links')
    )
    op.create_index('ix_contact_tag_links_tag', 'contact_tag_links', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_tag_links_tag', table_name='contact_tag_links')
    op.drop_table('contact_tag_links')
    op.drop_index('ix_contact_phones_normalized', table_name='contact_phones')
    op.drop_index('ix_contact_phones_contact', table_name='contact_phones')
    op.drop_table('contact_phones')
    op.drop_index('ix_ccr_requester', table_name='contact_change_requests')
    op.drop_index('ix_ccr_org_status', table_name='contact_change_requests')
    op.drop_index('ix_ccr_contact', table_name='contact_change_requests')
    op.drop_table('contact_change_requests')
    op.drop_index('ix_contacts_org_store', table_name='contacts')
    op.drop_index('ix_contacts_org_name_lower', table_name='contacts')
    op.drop_index('ix_contacts_org_deleted', table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('contact_tags')
    op.drop_index('ix_contact_audit_org_created', table_name='contact_audit_log')
    op.drop_index('ix_contact_audit_contact', table_name='contact_audit_log')
    op.drop_table('contact_audit_log')
    # ### end Alembic commands ###
