"""add accepting_signups and cover_photos to stores

Revision ID: 471d8bd82b49
Revises: 21c1e7c7afd2
Create Date: 2026-04-28 16:42:43.257908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '471d8bd82b49'
down_revision: Union[str, None] = '21c1e7c7afd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('accepting_signups', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('stores', sa.Column('cover_photos', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'cover_photos')
    op.drop_column('stores', 'accepting_signups')
    # ### end Alembic commands ###
