"""add reference_type to notifications

Revision ID: 4b6be2450395
Revises: 4bd62df2988f
Create Date: 2026-03-18 11:15:55.363439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6be2450395'
down_revision: Union[str, None] = '4bd62df2988f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('reference_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'reference_type')
    # ### end Alembic commands ###
