"""add email_verification_codes table

Revision ID: 4b979454682a
Revises: 2f1210f9aceb
Create Date: 2026-03-19 15:37:42.329815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b979454682a'
down_revision: Union[str, None] = '2f1210f9aceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('verification_token', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=20), server_default='registration', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evc_email_code', 'email_verification_codes', ['email', 'code'], unique=False)
    op.create_index('ix_evc_expires_at', 'email_verification_codes', ['expires_at'], unique=False)
    op.create_index('ix_evc_verification_token', 'email_verification_codes', ['verification_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evc_verification_token', table_name='email_verification_codes')
    op.drop_index('ix_evc_expires_at', table_name='email_verification_codes')
    op.drop_index('ix_evc_email_code', table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    # ### end Alembic commands ###
