"""체크리스트 인스턴스 점수 필드 및 cl_score_history 테이블 추가

Revision ID: 4bd62df2988f
Revises: 62eb4dd80ae0
Create Date: 2026-03-17 18:02:20.995930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bd62df2988f'
down_revision: Union[str, None] = '62eb4dd80ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl_score_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('old_score', sa.Integer(), nullable=True),
    sa.Column('new_score', sa.Integer(), nullable=False),
    sa.Column('old_score_note', sa.Text(), nullable=True),
    sa.Column('new_score_note', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['cl_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cl_score_history_instance_id', 'cl_score_history', ['instance_id'], unique=False)
    op.add_column('cl_instances', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('cl_instances', sa.Column('score_note', sa.Text(), nullable=True))
    op.add_column('cl_instances', sa.Column('scored_by', sa.Uuid(), nullable=True))
    op.add_column('cl_instances', sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'cl_instances', 'users', ['scored_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cl_instances', type_='foreignkey')
    op.drop_column('cl_instances', 'scored_at')
    op.drop_column('cl_instances', 'scored_by')
    op.drop_column('cl_instances', 'score_note')
    op.drop_column('cl_instances', 'score')
    op.drop_index('ix_cl_score_history_instance_id', table_name='cl_score_history')
    op.drop_table('cl_score_history')
    # ### end Alembic commands ###
