"""contacts multi-axis visibility targets

공개 대상을 매장 한 축 → 매장/직급/개인 3축 + 개인 제외로 일반화한다.
설계: docs/99_inbox/2026-08-15-연락처-다축-가시성-설계.md (V1~V7)

drop_table('contact_stores') 는 **의도된 삭제**다 (드리프트 아님).
이 브랜치 안에서만 존재했던 중간 테이블이라 백필 후 바로 지운다:
    1) contact_visibility_targets 생성
    2) contact_stores 행 → target_type='store' 로 백필
    3) visibility 값 'stores' → 'restricted'
    4) contact_stores 제거

position 축은 만들지 않았다 — 이 프로젝트에 "사용자의 직책"이 없다
(positions 는 매장별 근무 역할이라 사람 집합으로 풀리지 않는다).

Revision ID: 4cc62a42bcd8
Revises: ffbf5a12871e
Create Date: 2026-08-15 19:00:52.080333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cc62a42bcd8'
down_revision: Union[str, None] = 'ffbf5a12871e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_visibility_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('is_excluded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'target_type', 'target_id', name='uq_contact_visibility_targets')
    )
    op.create_index('ix_cvt_lookup', 'contact_visibility_targets', ['target_type', 'target_id'], unique=False)
    # --- 백필 (contact_stores 를 지우기 전에) ---
    op.execute(
        sa.text(
            """
            INSERT INTO contact_visibility_targets
                (id, contact_id, target_type, target_id, is_excluded, created_at)
            SELECT gen_random_uuid(), cs.contact_id, 'store', cs.store_id, false, now()
              FROM contact_stores cs
            """
        )
    )
    op.execute(sa.text("UPDATE contacts SET visibility = 'restricted' WHERE visibility = 'stores'"))

    op.drop_index('ix_contact_stores_store', table_name='contact_stores')
    op.drop_table('contact_stores')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_stores',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name='contact_stores_contact_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='contact_stores_store_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='contact_stores_pkey'),
    sa.UniqueConstraint('contact_id', 'store_id', name='uq_contact_stores')
    )
    op.create_index('ix_contact_stores_store', 'contact_stores', ['store_id'], unique=False)
    # 역백필 — store 축만 되돌릴 수 있다. role/user 대상과 제외는 **사라진다**(구조상 불가피).
    op.execute(
        sa.text(
            """
            INSERT INTO contact_stores (id, contact_id, store_id, created_at)
            SELECT gen_random_uuid(), t.contact_id, t.target_id, now()
              FROM contact_visibility_targets t
             WHERE t.target_type = 'store' AND t.is_excluded = false
            """
        )
    )
    op.execute(sa.text("UPDATE contacts SET visibility = 'stores' WHERE visibility = 'restricted'"))
    op.drop_index('ix_cvt_lookup', table_name='contact_visibility_targets')
    op.drop_table('contact_visibility_targets')
    # ### end Alembic commands ###
