"""application_reviews 테이블 추가 (평가자별 review)

Revision ID: 517555ebe532
Revises: 202bd106f406
Create Date: 2026-04-30 18:51:55.179106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517555ebe532'
down_revision: Union[str, None] = '202bd106f406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'reviewer_id', name='uq_review_per_application_reviewer')
    )
    op.create_index(op.f('ix_application_reviews_application_id'), 'application_reviews', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_reviews_reviewer_id'), 'application_reviews', ['reviewer_id'], unique=False)
    # NOTE: uq_store_form_one_draft 는 유지 (autogenerate 가 잘못 drop 으로 감지함)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_reviews_reviewer_id'), table_name='application_reviews')
    op.drop_index(op.f('ix_application_reviews_application_id'), table_name='application_reviews')
    op.drop_table('application_reviews')
    # ### end Alembic commands ###
