"""add rest break tracking setting

Revision ID: 5def010ca5a7
Revises: b6d39db7410c
Create Date: 2026-08-13 19:09:27.005699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5def010ca5a7'
down_revision: Union[str, None] = 'b6d39db7410c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_KEY = "payroll.rest_break_tracking"


def upgrade() -> None:
    op.execute(
        sa.text(
            """
            INSERT INTO settings_registry
                (key, label, description, value_type, default_value,
                 category, levels, default_priority, created_at, updated_at)
            VALUES
                (:key, 'Rest breaks are recorded',
                 'Turn on only if staff actually clock their paid 10-minute rest '
                 'breaks at this store. Rest-break penalties are detected by looking '
                 'for recorded breaks, so if they are never recorded every shift over '
                 '3.5 hours is flagged as a violation. When off, rest-break penalties '
                 'are not evaluated — there is no evidence either way.',
                 'boolean', CAST('false' AS jsonb), 'Payroll',
                 CAST('["org", "store"]' AS jsonb), 'item', now(), now())
            ON CONFLICT (key) DO NOTHING
            """
        ).bindparams(key=_KEY)
    )
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute(sa.text("DELETE FROM settings_registry WHERE key = :key").bindparams(key=_KEY))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
