"""add payload to schedule_report_snapshots

Revision ID: 627a32cf25db
Revises: a4820892e35f
Create Date: 2026-08-14 21:48:56.656018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '627a32cf25db'
down_revision: Union[str, None] = 'a4820892e35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_report_snapshots', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_report_snapshots', 'payload')
    # ### end Alembic commands ###
