"""add day_start_time, weekly_overtime_limit, hourly_rate fields

Revision ID: 628e82e4319b
Revises: 936f0b67898a
Create Date: 2026-03-30 10:19:18.765110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628e82e4319b'
down_revision: Union[str, None] = '936f0b67898a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('day_start_time', sa.Time(), nullable=True))
    op.add_column('organizations', sa.Column('weekly_overtime_limit', sa.Integer(), nullable=False, server_default='40'))
    op.add_column('schedules', sa.Column('hourly_rate_override', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hourly_rate')
    op.drop_column('schedules', 'hourly_rate_override')
    op.drop_column('organizations', 'weekly_overtime_limit')
    op.drop_column('organizations', 'day_start_time')
    # ### end Alembic commands ###
