"""cl_instance_items: remove note, location, resubmission_count

Revision ID: 62eb4dd80ae0
Revises: 9f555bf16184
Create Date: 2026-03-17 17:38:54.451264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62eb4dd80ae0'
down_revision: Union[str, None] = '9f555bf16184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cl_instance_items', 'location')
    op.drop_column('cl_instance_items', 'note')
    op.drop_column('cl_instance_items', 'resubmission_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cl_instance_items', sa.Column('resubmission_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cl_instance_items', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('cl_instance_items', sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
