"""org_member offboard fields (termination_reason, rehire_eligible)

부모 재연결(2026-08-14): dev 통합 시 d1e2l3i4v5r6 이 분기점이 되어 head 가 갈렸다.
프로젝트 관례대로 merge migration 대신 down_revision 을 dev head(2634e2879617) 위로
직렬 연결했다.

Revision ID: 6bf15e14f25a
Revises: d1e2l3i4v5r6
Create Date: 2026-08-13 23:44:52.483337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bf15e14f25a'
down_revision: Union[str, None] = 'a68dbdf22ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('org_members', sa.Column('termination_reason', sa.String(length=500), nullable=True))
    op.add_column('org_members', sa.Column('rehire_eligible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('org_members', 'rehire_eligible')
    op.drop_column('org_members', 'termination_reason')
    # ### end Alembic commands ###
