"""add headcount_by_day to store_work_roles

Revision ID: 6d47929bfc50
Revises: 7f846feeb44b
Create Date: 2026-03-30 21:05:52.463094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d47929bfc50'
down_revision: Union[str, None] = '7f846feeb44b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_work_roles', sa.Column('headcount_by_day', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_work_roles', 'headcount_by_day')
    # ### end Alembic commands ###
