"""add is_work_assignment to user_stores

Revision ID: 7a9b9d387a50
Revises: 46f7fd01335b
Create Date: 2026-04-22 11:08:31.836243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a9b9d387a50'
down_revision: Union[str, None] = '46f7fd01335b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_stores', sa.Column('is_work_assignment', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stores', 'is_work_assignment')
    # ### end Alembic commands ###
