"""empid change ledger + attendance correction channel

Revision ID: 7f25d2917fba
Revises: 4567c0f6971b
Create Date: 2026-08-15 13:18:04.413007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f25d2917fba'
down_revision: Union[str, None] = '4567c0f6971b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empid_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('store_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('person_name', sa.String(length=255), nullable=True),
    sa.Column('old_empid', sa.Integer(), nullable=True),
    sa.Column('new_empid', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_empid_changes_org_created', 'empid_changes', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_empid_changes_store', 'empid_changes', ['store_id'], unique=False)
    op.create_index('ix_empid_changes_user', 'empid_changes', ['user_id'], unique=False)
    op.add_column('attendance_corrections', sa.Column('channel', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_corrections', 'channel')
    op.drop_index('ix_empid_changes_user', table_name='empid_changes')
    op.drop_index('ix_empid_changes_store', table_name='empid_changes')
    op.drop_index('ix_empid_changes_org_created', table_name='empid_changes')
    op.drop_table('empid_changes')
    # ### end Alembic commands ###
