"""add session info to refresh_tokens

Revision ID: 8353eb507e17
Revises: 9134b2a4d407
Create Date: 2026-03-19 11:09:05.886138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8353eb507e17'
down_revision: Union[str, None] = '9134b2a4d407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('refresh_tokens', sa.Column('client_type', sa.String(length=20), server_default='unknown', nullable=False))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=512), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    # last_used_at: add as nullable, backfill from created_at, then set NOT NULL
    op.add_column('refresh_tokens', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE refresh_tokens SET last_used_at = created_at WHERE last_used_at IS NULL")
    op.alter_column('refresh_tokens', 'last_used_at', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'client_type')
    # ### end Alembic commands ###
