"""add reported_at to cl_instances

Revision ID: 9134b2a4d407
Revises: 4b6be2450395
Create Date: 2026-03-18 11:23:16.060816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9134b2a4d407'
down_revision: Union[str, None] = '4b6be2450395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cl_instances', sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cl_instances', 'reported_at')
    # ### end Alembic commands ###
