"""Phase 1B fix: review_log comment + files FK (review_log_id, message_id)

Revision ID: 93bcc7ba20e8
Revises: d77dcdfdd7f3
Create Date: 2026-03-17 16:21:41.526613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93bcc7ba20e8'
down_revision: Union[str, None] = 'd77dcdfdd7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cl_item_files', sa.Column('review_log_id', sa.Uuid(), nullable=True))
    op.add_column('cl_item_files', sa.Column('message_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'cl_item_files', 'cl_item_messages', ['message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cl_item_files', 'cl_item_reviews_log', ['review_log_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cl_item_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('cl_item_messages', 'type')
    op.add_column('cl_item_reviews_log', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cl_item_reviews_log', 'comment')
    op.add_column('cl_item_messages', sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.alter_column('cl_item_messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'cl_item_files', type_='foreignkey')
    op.drop_constraint(None, 'cl_item_files', type_='foreignkey')
    op.drop_column('cl_item_files', 'message_id')
    op.drop_column('cl_item_files', 'review_log_id')
    # ### end Alembic commands ###
