"""schedule audit log acknowledged warnings

Revision ID: 93e5d4c4a7fd
Revises: ec00db074174
Create Date: 2026-08-10 18:30:56.689823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93e5d4c4a7fd'
down_revision: Union[str, None] = 'ec00db074174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_audit_logs', sa.Column('acknowledged_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_audit_logs', 'acknowledged_warnings')
    # ### end Alembic commands ###
