"""contacts audit source and batch id

Revision ID: a68dbdf22ab7
Revises: 4cc62a42bcd8
Create Date: 2026-08-15 22:20:26.310928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68dbdf22ab7'
down_revision: Union[str, None] = '4cc62a42bcd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_audit_log', sa.Column('source', sa.String(length=16), server_default='direct', nullable=False))
    op.add_column('contact_audit_log', sa.Column('batch_id', sa.Uuid(), nullable=True))
    op.create_index('ix_contact_audit_batch', 'contact_audit_log', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_audit_batch', table_name='contact_audit_log')
    op.drop_column('contact_audit_log', 'batch_id')
    op.drop_column('contact_audit_log', 'source')
    # ### end Alembic commands ###
