"""add is_archived to checklist_templates

Revision ID: b38ea3c44b97
Revises: 7a9b9d387a50
Create Date: 2026-04-22 16:22:17.035988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38ea3c44b97'
down_revision: Union[str, None] = '7a9b9d387a50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_templates', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_templates', 'is_archived')
    # ### end Alembic commands ###
