"""add app_versions table

Revision ID: b476eab64f72
Revises: 471d8bd82b49
Create Date: 2026-04-29 17:03:20.080365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b476eab64f72'
down_revision: Union[str, None] = '471d8bd82b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('is_min_required', sa.Boolean(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_versions_channel', 'app_versions', ['channel'], unique=False)
    op.create_index('ix_app_versions_channel_latest', 'app_versions', ['channel', 'is_latest'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_versions_channel_latest', table_name='app_versions')
    op.drop_index('ix_app_versions_channel', table_name='app_versions')
    op.drop_table('app_versions')
    # ### end Alembic commands ###
