"""tip allocations table for hours-prorated distribution

Revision ID: b6d39db7410c
Revises: b3f7c2a91d40
Create Date: 2026-08-11 23:39:14.202083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d39db7410c'
down_revision: Union[str, None] = 'b3f7c2a91d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('card_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weight_minutes', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'employee_id', 'date', name='uq_tip_allocation_day')
    )
    op.create_index('ix_tip_allocation_store_date', 'tip_allocations', ['store_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tip_allocation_store_date', table_name='tip_allocations')
    op.drop_table('tip_allocations')
    # ### end Alembic commands ###
