"""Phase 1A: FK cleanup + soft delete + constraints

Revision ID: be43ef1afc44
Revises: e83c58015efe
Create Date: 2026-03-17 15:57:18.605445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be43ef1afc44'
down_revision: Union[str, None] = 'e83c58015efe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cl_comments_instance', table_name='cl_comments')
    op.drop_table('cl_comments')
    op.drop_table('cl_template_links')
    op.alter_column('additional_task_assignees', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_additional_task_assignee', 'additional_task_assignees', ['task_id', 'user_id'])
    op.drop_constraint('additional_task_assignees_user_id_fkey', 'additional_task_assignees', type_='foreignkey')
    op.create_foreign_key(None, 'additional_task_assignees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('additional_tasks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('additional_tasks', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('additional_tasks_created_by_fkey', 'additional_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'additional_tasks', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('announcement_reads', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_announcement_read_user', 'announcement_reads', type_='unique')
    op.create_unique_constraint('uq_announcement_read', 'announcement_reads', ['announcement_id', 'user_id'])
    op.add_column('announcements', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('announcements', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('announcements_created_by_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.alter_column('attendance_corrections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('attendances', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('attendances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_attendances_org_store_date', table_name='attendances')
    op.drop_index('ix_attendances_user_date', table_name='attendances')
    op.drop_constraint('attendances_user_id_fkey', 'attendances', type_='foreignkey')
    op.drop_constraint('attendances_store_id_fkey', 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'attendances', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cl_completions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cl_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cl_completions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('cl_completions_user_id_fkey', 'cl_completions', type_='foreignkey')
    op.create_foreign_key(None, 'cl_completions', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cl_instances', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cl_instances', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('cl_instances', 'total_items',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cl_instances', 'completed_items',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('cl_instances', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('cl_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cl_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_cl_instances_org_id', table_name='cl_instances')
    op.drop_index('ix_cl_instances_store_date', table_name='cl_instances')
    op.drop_index('ix_cl_instances_user_date', table_name='cl_instances')
    op.drop_constraint('cl_instances_user_id_fkey', 'cl_instances', type_='foreignkey')
    op.drop_constraint('cl_instances_store_id_fkey', 'cl_instances', type_='foreignkey')
    op.create_foreign_key(None, 'cl_instances', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'cl_instances', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cl_item_reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_cl_item_reviews_instance', table_name='cl_item_reviews')
    op.drop_constraint('cl_item_reviews_reviewer_id_fkey', 'cl_item_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'cl_item_reviews', 'users', ['reviewer_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cl_review_contents', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_cl_review_contents_review', table_name='cl_review_contents')
    op.drop_constraint('cl_review_contents_author_id_fkey', 'cl_review_contents', type_='foreignkey')
    op.create_foreign_key(None, 'cl_review_contents', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('cl_review_history', 'changed_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('cl_review_history_changed_by_fkey', 'cl_review_history', type_='foreignkey')
    op.create_foreign_key(None, 'cl_review_history', 'users', ['changed_by'], ['id'], ondelete='SET NULL')
    op.alter_column('daily_report_comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('daily_report_comments_user_id_fkey', 'daily_report_comments', type_='foreignkey')
    op.create_foreign_key(None, 'daily_report_comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('daily_report_templates', 'organization_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('daily_reports', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('daily_reports', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('daily_reports', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('daily_reports_author_id_fkey', 'daily_reports', type_='foreignkey')
    op.create_foreign_key(None, 'daily_reports', 'users', ['author_id'], ['id'], ondelete='SET NULL')
    op.alter_column('eval_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('eval_template_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('eval_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('eval_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('evaluations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('evaluations', 'evaluator_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('evaluations', 'evaluatee_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_evaluations_org_evaluatee', table_name='evaluations')
    op.drop_constraint('evaluations_evaluatee_id_fkey', 'evaluations', type_='foreignkey')
    op.drop_constraint('evaluations_evaluator_id_fkey', 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'users', ['evaluatee_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'evaluations', 'users', ['evaluator_id'], ['id'], ondelete='SET NULL')
    op.alter_column('labor_law_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor_law_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('uq_labor_law_org_store', 'labor_law_settings', type_='unique')
    op.drop_column('notifications', 'reference_type')
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('idx_permissions_resource_action', table_name='permissions')
    op.create_unique_constraint('idx_permissions_resource_action', 'permissions', ['resource', 'action'])
    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_qr_codes_store', table_name='qr_codes')
    op.drop_index('idx_role_permissions_role_id', table_name='role_permissions')
    op.alter_column('schedule_requests', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('schedule_requests_user_id_fkey', 'schedule_requests', type_='foreignkey')
    op.create_foreign_key(None, 'schedule_requests', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('schedules', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('schedules', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('schedule_entries_store_id_fkey', 'schedules', type_='foreignkey')
    op.drop_constraint('schedule_entries_user_id_fkey', 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'schedules', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    op.alter_column('shift_presets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shift_presets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_shift_presets_store_shift', table_name='shift_presets')
    op.add_column('stores', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('task_evidences', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('task_evidences', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'photo'::character varying"))
    op.alter_column('task_evidences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_task_evidences_task_id', table_name='task_evidences')
    op.drop_constraint('task_evidences_user_id_fkey', 'task_evidences', type_='foreignkey')
    op.create_foreign_key(None, 'task_evidences', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('failed_login_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('voices', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('voices', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_issue_reports_org_id', table_name='voices')
    op.drop_index('ix_voices_created_by', table_name='voices')
    op.drop_index('ix_voices_status', table_name='voices')
    op.drop_constraint('issue_reports_resolved_by_fkey', 'voices', type_='foreignkey')
    op.drop_constraint('issue_reports_created_by_fkey', 'voices', type_='foreignkey')
    op.create_foreign_key(None, 'voices', 'users', ['resolved_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'voices', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voices', type_='foreignkey')
    op.drop_constraint(None, 'voices', type_='foreignkey')
    op.create_foreign_key('issue_reports_created_by_fkey', 'voices', 'users', ['created_by'], ['id'])
    op.create_foreign_key('issue_reports_resolved_by_fkey', 'voices', 'users', ['resolved_by'], ['id'])
    op.create_index('ix_voices_status', 'voices', ['status'], unique=False)
    op.create_index('ix_voices_created_by', 'voices', ['created_by'], unique=False)
    op.create_index('ix_issue_reports_org_id', 'voices', ['organization_id'], unique=False)
    op.alter_column('voices', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('voices', 'deleted_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'locked_at')
    op.drop_column('users', 'failed_login_count')
    op.drop_constraint(None, 'task_evidences', type_='foreignkey')
    op.create_foreign_key('task_evidences_user_id_fkey', 'task_evidences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_task_evidences_task_id', 'task_evidences', ['task_id'], unique=False)
    op.alter_column('task_evidences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_evidences', 'file_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'photo'::character varying"))
    op.alter_column('task_evidences', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('stores', 'deleted_at')
    op.create_index('ix_shift_presets_store_shift', 'shift_presets', ['store_id', 'shift_id'], unique=False)
    op.alter_column('shift_presets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shift_presets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key('schedule_entries_user_id_fkey', 'schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('schedule_entries_store_id_fkey', 'schedules', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.alter_column('schedules', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('schedules', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'schedule_requests', type_='foreignkey')
    op.create_foreign_key('schedule_requests_user_id_fkey', 'schedule_requests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('schedule_requests', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_role_permissions_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_index('ix_qr_codes_store', 'qr_codes', ['store_id'], unique=False)
    op.alter_column('qr_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('idx_permissions_resource_action', 'permissions', type_='unique')
    op.create_index('idx_permissions_resource_action', 'permissions', ['resource', 'action'], unique=False)
    op.drop_column('organizations', 'deleted_at')
    op.add_column('notifications', sa.Column('reference_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_unique_constraint('uq_labor_law_org_store', 'labor_law_settings', ['organization_id', 'store_id'])
    op.alter_column('labor_law_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('labor_law_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key('evaluations_evaluator_id_fkey', 'evaluations', 'users', ['evaluator_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('evaluations_evaluatee_id_fkey', 'evaluations', 'users', ['evaluatee_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_evaluations_org_evaluatee', 'evaluations', ['organization_id', 'evaluatee_id'], unique=False)
    op.alter_column('evaluations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('evaluations', 'evaluatee_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('evaluations', 'evaluator_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('evaluations', 'deleted_at')
    op.alter_column('eval_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('eval_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('eval_template_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('eval_responses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.create_foreign_key('daily_reports_author_id_fkey', 'daily_reports', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.alter_column('daily_reports', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('daily_reports', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('daily_reports', 'deleted_at')
    op.alter_column('daily_report_templates', 'organization_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'daily_report_comments', type_='foreignkey')
    op.create_foreign_key('daily_report_comments_user_id_fkey', 'daily_report_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('daily_report_comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'cl_review_history', type_='foreignkey')
    op.create_foreign_key('cl_review_history_changed_by_fkey', 'cl_review_history', 'users', ['changed_by'], ['id'], ondelete='CASCADE')
    op.alter_column('cl_review_history', 'changed_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'cl_review_contents', type_='foreignkey')
    op.create_foreign_key('cl_review_contents_author_id_fkey', 'cl_review_contents', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_cl_review_contents_review', 'cl_review_contents', ['review_id'], unique=False)
    op.alter_column('cl_review_contents', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'cl_item_reviews', type_='foreignkey')
    op.create_foreign_key('cl_item_reviews_reviewer_id_fkey', 'cl_item_reviews', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_cl_item_reviews_instance', 'cl_item_reviews', ['instance_id'], unique=False)
    op.alter_column('cl_item_reviews', 'reviewer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'cl_instances', type_='foreignkey')
    op.drop_constraint(None, 'cl_instances', type_='foreignkey')
    op.create_foreign_key('cl_instances_store_id_fkey', 'cl_instances', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('cl_instances_user_id_fkey', 'cl_instances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_cl_instances_user_date', 'cl_instances', ['user_id', 'work_date'], unique=False)
    op.create_index('ix_cl_instances_store_date', 'cl_instances', ['store_id', 'work_date'], unique=False)
    op.create_index('ix_cl_instances_org_id', 'cl_instances', ['organization_id'], unique=False)
    op.alter_column('cl_instances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cl_instances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cl_instances', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('cl_instances', 'completed_items',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cl_instances', 'total_items',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('cl_instances', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('cl_instances', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'cl_completions', type_='foreignkey')
    op.create_foreign_key('cl_completions_user_id_fkey', 'cl_completions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('cl_completions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cl_completions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cl_completions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key('attendances_store_id_fkey', 'attendances', 'stores', ['store_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('attendances_user_id_fkey', 'attendances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_attendances_user_date', 'attendances', ['user_id', 'work_date'], unique=False)
    op.create_index('ix_attendances_org_store_date', 'attendances', ['organization_id', 'store_id', 'work_date'], unique=False)
    op.alter_column('attendances', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('attendances', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendances', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('attendance_corrections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key('announcements_created_by_fkey', 'announcements', 'users', ['created_by'], ['id'])
    op.alter_column('announcements', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('announcements', 'deleted_at')
    op.drop_constraint('uq_announcement_read', 'announcement_reads', type_='unique')
    op.create_unique_constraint('uq_announcement_read_user', 'announcement_reads', ['announcement_id', 'user_id'])
    op.alter_column('announcement_reads', 'read_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'additional_tasks', type_='foreignkey')
    op.create_foreign_key('additional_tasks_created_by_fkey', 'additional_tasks', 'users', ['created_by'], ['id'])
    op.alter_column('additional_tasks', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('additional_tasks', 'deleted_at')
    op.drop_constraint(None, 'additional_task_assignees', type_='foreignkey')
    op.create_foreign_key('additional_task_assignees_user_id_fkey', 'additional_task_assignees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_additional_task_assignee', 'additional_task_assignees', type_='unique')
    op.alter_column('additional_task_assignees', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('cl_template_links',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shift_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('position_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('repeat_type', sa.VARCHAR(length=10), server_default=sa.text("'daily'::character varying"), autoincrement=False, nullable=False),
    sa.Column('repeat_days', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='cl_template_links_position_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='cl_template_links_shift_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='cl_template_links_store_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], name='cl_template_links_template_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cl_template_links_pkey'),
    sa.UniqueConstraint('template_id', 'store_id', 'shift_id', 'position_id', name='uq_cl_template_link')
    )
    op.create_table('cl_comments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['cl_instances.id'], name='cl_comments_instance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cl_comments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cl_comments_pkey')
    )
    op.create_index('ix_cl_comments_instance', 'cl_comments', ['instance_id'], unique=False)
    # ### end Alembic commands ###
