"""payroll phase2: pay_periods, payroll_entries, payroll_events

Revision ID: c659422e16ae
Revises: b77039450fd5
Create Date: 2026-08-03 19:50:31.706811

Payroll v1 Phase 2 스키마 (스펙: docs/99_inbox/2026-08-03 payroll-v1-스키마-스펙.md §4/§5/§6):
    1. pay_periods — 매장별 반월 정산 기간 ('open' → 'confirmed', store RESTRICT)
    2. payroll_entries — confirm 시 동결되는 직원별 스냅샷 (breakdown JSONB + revision)
    3. payroll_events — penalty/OT 일 단위 이벤트 + 귀책 태그 (voided_at soft-void)

Note: autogenerate 가 감지한 무관 drift(레거시 announcements/notifications drop,
users.notification_preferences, file_usages.sort_order, 인덱스 diff 등)는 제거 —
이 revision 은 payroll 3개 테이블만 다룬다.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c659422e16ae'
down_revision: Union[str, None] = 'b77039450fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_periods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'start_date', name='uq_pay_period_store_start')
    )
    op.create_index(op.f('ix_pay_periods_organization_id'), 'pay_periods', ['organization_id'], unique=False)
    op.create_table('payroll_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pay_period_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('org_member_id', sa.Uuid(), nullable=True),
    sa.Column('empid', sa.Integer(), nullable=True),
    sa.Column('crewid', sa.Integer(), nullable=True),
    sa.Column('member_name', sa.String(length=255), nullable=False),
    sa.Column('revision', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('regular_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('ot_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dt_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('regular_pay', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('ot_pay', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('dt_pay', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('penalty_pay', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('card_tips', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('gross_pay', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('calc_version', sa.Integer(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_member_id'], ['org_members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_entries_organization_id'), 'payroll_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_pay_period_id'), 'payroll_entries', ['pay_period_id'], unique=False)
    op.create_index('uq_payroll_entry_period_user_rev', 'payroll_entries', ['pay_period_id', 'user_id', 'revision'], unique=True, postgresql_where='user_id IS NOT NULL')
    op.create_table('payroll_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('attendance_id', sa.Uuid(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('attribution', sa.String(length=20), nullable=True),
    sa.Column('tagged_by', sa.Uuid(), nullable=True),
    sa.Column('tagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pay_period_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pay_period_id'], ['pay_periods.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tagged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_events_organization_id'), 'payroll_events', ['organization_id'], unique=False)
    op.create_index('ix_payroll_events_store_date', 'payroll_events', ['store_id', 'work_date'], unique=False)
    op.create_index('ix_payroll_events_user_date', 'payroll_events', ['user_id', 'work_date'], unique=False)
    op.create_index('uq_payroll_event_user_date_kind', 'payroll_events', ['organization_id', 'user_id', 'work_date', 'kind'], unique=True, postgresql_where='user_id IS NOT NULL')


def downgrade() -> None:
    op.drop_index('uq_payroll_event_user_date_kind', table_name='payroll_events', postgresql_where='user_id IS NOT NULL')
    op.drop_index('ix_payroll_events_user_date', table_name='payroll_events')
    op.drop_index('ix_payroll_events_store_date', table_name='payroll_events')
    op.drop_index(op.f('ix_payroll_events_organization_id'), table_name='payroll_events')
    op.drop_table('payroll_events')
    op.drop_index('uq_payroll_entry_period_user_rev', table_name='payroll_entries', postgresql_where='user_id IS NOT NULL')
    op.drop_index(op.f('ix_payroll_entries_pay_period_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_organization_id'), table_name='payroll_entries')
    op.drop_table('payroll_entries')
    op.drop_index(op.f('ix_pay_periods_organization_id'), table_name='pay_periods')
    op.drop_table('pay_periods')
    # ### end Alembic commands ###
