"""phase_1c_daily_report_sections_jsonb_to_rows

Revision ID: d77dcdfdd7f3
Revises: fad7d7752003
Create Date: 2026-03-17 16:14:15.354587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd77dcdfdd7f3'
down_revision: Union[str, None] = 'fad7d7752003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report_sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('template_section_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['daily_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_section_id'], ['daily_report_template_sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )

    # Migrate existing JSONB data to daily_report_sections rows
    op.execute("""
        INSERT INTO daily_report_sections (id, report_id, template_section_id, title, content, sort_order, created_at, updated_at)
        SELECT
            gen_random_uuid(),
            r.id AS report_id,
            NULL AS template_section_id,
            COALESCE(section->>'title', 'Section') AS title,
            section->>'content' AS content,
            COALESCE((section->>'sort_order')::int, 0) AS sort_order,
            NOW() AS created_at,
            NOW() AS updated_at
        FROM daily_reports r,
             jsonb_array_elements(
                 CASE
                     WHEN r.sections_data IS NULL OR jsonb_typeof(r.sections_data) != 'array' THEN '[]'::jsonb
                     ELSE r.sections_data
                 END
             ) AS section
        WHERE r.sections_data IS NOT NULL
          AND jsonb_typeof(r.sections_data) = 'array'
          AND jsonb_array_length(r.sections_data) > 0
    """)

    op.drop_column('daily_reports', 'sections_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_reports', sa.Column('sections_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))

    # Restore JSONB data from daily_report_sections rows
    op.execute("""
        UPDATE daily_reports r
        SET sections_data = (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'title', s.title,
                    'content', s.content,
                    'sort_order', s.sort_order
                ) ORDER BY s.sort_order
            )
            FROM daily_report_sections s
            WHERE s.report_id = r.id
        )
    """)

    op.drop_table('daily_report_sections')
    # ### end Alembic commands ###
