"""store group code

Revision ID: e3cbb0d54b55
Revises: b3edc09dc96c
Create Date: 2026-08-15 16:26:01.392456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cbb0d54b55'
down_revision: Union[str, None] = 'b3edc09dc96c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_groups', sa.Column('code', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_groups', 'code')
    # ### end Alembic commands ###
