"""add attendance_breaks table

Revision ID: eaadd6aa7b9f
Revises: 2ab49c216eb8
Create Date: 2026-04-22 18:19:25.135626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaadd6aa7b9f'
down_revision: Union[str, None] = '2ab49c216eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_breaks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attendance_id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('break_type', sa.String(length=16), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_breaks_attendance_open', 'attendance_breaks', ['attendance_id', 'ended_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_breaks_attendance_open', table_name='attendance_breaks')
    op.drop_table('attendance_breaks')
    # ### end Alembic commands ###
