"""drop schedules request_id fk to legacy schedule_requests

스케줄 신청 기능 폐기(2026-08-09)로 ScheduleRequest 모델을 제거했다.
테이블 자체는 이력 보존을 위해 남기고 alembic/env.py LEGACY_TABLES 에 등록했지만,
`schedules.request_id` 의 FK 제약은 모델에서 사라졌으므로 DB 에서도 뗀다.

**의도된 drop_constraint 다** (CLAUDE.md 규칙 6 확인 완료):
  - 컬럼과 값은 그대로 둔다. 참조 무결성 강제만 사라진다.
  - 나중에 legacy 테이블을 실제로 드롭하려면 이 FK 가 먼저 없어져야 한다.

Revision ID: ec00db074174
Revises: 32cee939a99a
Create Date: 2026-08-10 18:14:17.346121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec00db074174'
down_revision: Union[str, None] = '32cee939a99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schedule_entries_request_id_fkey', 'schedules', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('schedule_entries_request_id_fkey', 'schedules', 'schedule_requests', ['request_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
