"""Phase 1B checklist 9to6 table restructure

Revision ID: fad7d7752003
Revises: be43ef1afc44
Create Date: 2026-03-17 16:08:37.474648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fad7d7752003'
down_revision: Union[str, None] = 'be43ef1afc44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cl_instance_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instance_id', sa.Uuid(), nullable=False),
    sa.Column('item_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_type', sa.String(length=20), nullable=False),
    sa.Column('min_photos', sa.Integer(), nullable=False),
    sa.Column('max_photos', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_tz', sa.String(length=50), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resubmission_count', sa.Integer(), nullable=False),
    sa.Column('review_result', sa.String(length=20), nullable=True),
    sa.Column('reviewer_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instance_id'], ['cl_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance_id', 'item_index', name='uq_cl_instance_item_index')
    )
    op.create_index('ix_cl_instance_items_instance_id', 'cl_instance_items', ['instance_id'], unique=False)
    op.create_table('cl_item_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['cl_instance_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cl_item_messages_item_id', 'cl_item_messages', ['item_id'], unique=False)
    op.create_table('cl_item_reviews_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('old_result', sa.String(length=20), nullable=True),
    sa.Column('new_result', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['cl_instance_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cl_item_reviews_log_item_id', 'cl_item_reviews_log', ['item_id'], unique=False)
    op.create_table('cl_item_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['cl_instance_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cl_item_submissions_item_id', 'cl_item_submissions', ['item_id'], unique=False)
    op.create_table('cl_item_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['cl_instance_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['cl_item_submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cl_item_files_item_id', 'cl_item_files', ['item_id'], unique=False)

    # ---------------------------------------------------------------------------
    # Data migration: populate new tables from old structure
    # ---------------------------------------------------------------------------

    # 1. snapshot JSONB → cl_instance_items (only instances that have a snapshot)
    op.execute("""
        INSERT INTO cl_instance_items (
            id, instance_id, item_index, title, description,
            verification_type, min_photos, sort_order, is_completed, resubmission_count,
            created_at, updated_at
        )
        SELECT
            gen_random_uuid(),
            ci.id,
            (item->>'item_index')::int,
            COALESCE(item->>'title', ''),
            item->>'description',
            COALESCE(item->>'verification_type', 'none'),
            0,
            COALESCE((item->>'sort_order')::int, (item->>'item_index')::int, 0),
            false,
            0,
            ci.created_at,
            ci.created_at
        FROM cl_instances ci,
             jsonb_array_elements(ci.snapshot->'items') AS item
        WHERE ci.snapshot IS NOT NULL
          AND ci.snapshot ? 'items'
    """)

    # 2. Merge completion data into cl_instance_items
    op.execute("""
        UPDATE cl_instance_items cii
        SET is_completed    = true,
            completed_at    = cc.completed_at,
            completed_tz    = cc.completed_timezone,
            completed_by    = cc.user_id,
            note            = cc.note,
            location        = cc.location,
            resubmission_count = cc.resubmission_count
        FROM cl_completions cc
        WHERE cii.instance_id = cc.instance_id
          AND cii.item_index  = cc.item_index
    """)

    # 2.5. Create initial submission (version=0) for all completed items
    #      so that chat timeline shows "Submitted" event with photo+text
    op.execute("""
        INSERT INTO cl_item_submissions (
            id, item_id, version, note, location, submitted_by, submitted_at, created_at
        )
        SELECT
            gen_random_uuid(),
            cii.id,
            0,
            cc.note,
            cc.location,
            cc.user_id,
            cc.completed_at,
            cc.completed_at
        FROM cl_completions cc
        JOIN cl_instance_items cii
          ON cii.instance_id = cc.instance_id AND cii.item_index = cc.item_index
    """)

    # 3. Migrate current completion photo → cl_item_files (linked to initial submission)
    op.execute("""
        INSERT INTO cl_item_files (id, item_id, submission_id, file_url, file_type, sort_order, uploaded_by, created_at)
        SELECT gen_random_uuid(), cii.id, cis.id, cc.photo_url, 'photo', 0, cc.user_id, cc.completed_at
        FROM cl_completions cc
        JOIN cl_instance_items cii
          ON cii.instance_id = cc.instance_id AND cii.item_index = cc.item_index
        JOIN cl_item_submissions cis
          ON cis.item_id = cii.id AND cis.version = 0
        WHERE cc.photo_url IS NOT NULL
    """)

    # 4. Merge review data into cl_instance_items
    op.execute("""
        UPDATE cl_instance_items cii
        SET review_result = cr.result,
            reviewer_id   = cr.reviewer_id,
            reviewed_at   = cr.updated_at
        FROM cl_item_reviews cr
        WHERE cii.instance_id = cr.instance_id
          AND cii.item_index  = cr.item_index
    """)

    # 5. Migrate cl_completion_history → cl_item_submissions
    op.execute("""
        INSERT INTO cl_item_submissions (
            id, item_id, version, note, location, submitted_by, submitted_at, created_at
        )
        SELECT
            gen_random_uuid(),
            cii.id,
            ROW_NUMBER() OVER (PARTITION BY cii.id ORDER BY ch.submitted_at),
            ch.note,
            ch.location,
            cc.user_id,
            ch.submitted_at,
            ch.created_at
        FROM cl_completion_history ch
        JOIN cl_completions cc ON ch.completion_id = cc.id
        JOIN cl_instance_items cii
          ON cii.instance_id = cc.instance_id AND cii.item_index = cc.item_index
    """)

    # 6. Migrate cl_completion_history photos → cl_item_files linked to their submission
    op.execute("""
        INSERT INTO cl_item_files (id, item_id, submission_id, file_url, file_type, sort_order, uploaded_by, created_at)
        SELECT gen_random_uuid(), cis.item_id, cis.id, ch.photo_url, 'photo', 0, cis.submitted_by, ch.created_at
        FROM cl_completion_history ch
        JOIN cl_completions cc ON ch.completion_id = cc.id
        JOIN cl_instance_items cii
          ON cii.instance_id = cc.instance_id AND cii.item_index = cc.item_index
        JOIN cl_item_submissions cis
          ON cis.item_id = cii.id AND cis.submitted_at = ch.submitted_at
        WHERE ch.photo_url IS NOT NULL
    """)

    # 7. Migrate cl_review_history → cl_item_reviews_log
    op.execute("""
        INSERT INTO cl_item_reviews_log (id, item_id, old_result, new_result, changed_by, created_at)
        SELECT gen_random_uuid(), cii.id, rh.old_result, rh.new_result, rh.changed_by, rh.created_at
        FROM cl_review_history rh
        JOIN cl_item_reviews cr ON rh.review_id = cr.id
        JOIN cl_instance_items cii
          ON cii.instance_id = cr.instance_id AND cii.item_index = cr.item_index
    """)

    # 8. Migrate cl_review_contents → cl_item_messages (linked via review)
    op.execute("""
        INSERT INTO cl_item_messages (id, item_id, author_id, type, content, created_at)
        SELECT gen_random_uuid(), cii.id, rc.author_id, rc.type, rc.content, rc.created_at
        FROM cl_review_contents rc
        JOIN cl_item_reviews cr ON rc.review_id = cr.id
        JOIN cl_instance_items cii
          ON cii.instance_id = cr.instance_id AND cii.item_index = cr.item_index
    """)

    # ---------------------------------------------------------------------------
    # Drop old tables (after data migration)
    # ---------------------------------------------------------------------------
    op.drop_table('cl_review_contents')
    op.drop_table('cl_review_history')
    op.drop_table('cl_item_reviews')
    op.drop_table('cl_completion_history')
    op.drop_table('cl_completions')
    op.drop_column('cl_instances', 'snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cl_instances', sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('cl_review_contents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name='cl_review_contents_author_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['cl_item_reviews.id'], name='cl_review_contents_review_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cl_review_contents_pkey')
    )
    op.create_table('cl_completions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('completed_timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('resubmission_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['cl_instances.id'], name='cl_completions_instance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cl_completions_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='cl_completions_pkey'),
    sa.UniqueConstraint('instance_id', 'item_index', name='uq_cl_completion_instance_item'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cl_review_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_result', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('new_result', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='cl_review_history_changed_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['review_id'], ['cl_item_reviews.id'], name='cl_review_history_review_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cl_review_history_pkey')
    )
    op.create_table('cl_item_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instance_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('result', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['cl_instances.id'], name='cl_item_reviews_instance_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name='cl_item_reviews_reviewer_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='cl_item_reviews_pkey'),
    sa.UniqueConstraint('instance_id', 'item_index', name='uq_cl_item_review_instance_item')
    )
    op.create_table('cl_completion_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('completion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('photo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['completion_id'], ['cl_completions.id'], name='cl_completion_history_completion_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='cl_completion_history_pkey')
    )
    op.drop_index('ix_cl_item_files_item_id', table_name='cl_item_files')
    op.drop_table('cl_item_files')
    op.drop_index('ix_cl_item_submissions_item_id', table_name='cl_item_submissions')
    op.drop_table('cl_item_submissions')
    op.drop_index('ix_cl_item_reviews_log_item_id', table_name='cl_item_reviews_log')
    op.drop_table('cl_item_reviews_log')
    op.drop_index('ix_cl_item_messages_item_id', table_name='cl_item_messages')
    op.drop_table('cl_item_messages')
    op.drop_index('ix_cl_instance_items_instance_id', table_name='cl_instance_items')
    op.drop_table('cl_instance_items')
    # ### end Alembic commands ###
