"""contacts multi-store visibility

연락처 가시성을 단일 store_id → 명시 모드(visibility) + 다대다(contact_stores) 로 옮긴다.
계약 개정: docs/99_inbox/2026-08-14-연락처-API계약.md §0-A
설계: docs/99_inbox/2026-08-15-연락처-복수매장-가시성-확장.md (D1, D4)

drop_column('contacts.store_id') 은 **의도된 삭제**다 (드리프트 아님).
백필을 이 마이그레이션 안에서 끝내고 지운다 — 배포 서버에서도 같은 순서로 돌아야 한다:
    1) contact_stores 생성 + visibility 컬럼 추가 (기본값 'organization')
    2) store_id 값이 있던 행만 → visibility='stores' + contact_stores 1건
       (기존 store_id NULL = 전체 공유 였으므로 기본값 그대로 두면 맞다)
    3) store_id 제거

Revision ID: ffbf5a12871e
Revises: 2634e2879617
Create Date: 2026-08-15 13:07:02.913227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbf5a12871e'
down_revision: Union[str, None] = '2634e2879617'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'store_id', name='uq_contact_stores')
    )
    op.create_index('ix_contact_stores_store', 'contact_stores', ['store_id'], unique=False)
    op.add_column('contacts', sa.Column('visibility', sa.String(length=16), server_default='organization', nullable=False))
    op.drop_index('ix_contacts_org_store', table_name='contacts')
    op.create_index('ix_contacts_org_visibility', 'contacts', ['organization_id', 'visibility'], unique=False)
    # ### end Alembic commands ###

    # --- 백필 (store_id 를 지우기 전에) ---
    # 매장이 지정돼 있던 연락처만 'stores' 모드로 옮긴다. store_id 가 NULL 이던 행은
    # 전체 공유였고 visibility 기본값이 'organization' 이므로 손댈 것이 없다.
    op.execute(
        sa.text(
            """
            INSERT INTO contact_stores (id, contact_id, store_id, created_at)
            SELECT gen_random_uuid(), c.id, c.store_id, now()
              FROM contacts c
             WHERE c.store_id IS NOT NULL
            """
        )
    )
    op.execute(
        sa.text(
            """
            UPDATE contacts
               SET visibility = 'stores'
             WHERE store_id IS NOT NULL
            """
        )
    )

    op.drop_constraint('contacts_store_id_fkey', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'store_id')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('contacts_store_id_fkey', 'contacts', 'stores', ['store_id'], ['id'], ondelete='SET NULL')
    # 역백필 — 단일 컬럼이라 담을 수 있는 건 매장 하나뿐이다. 복수 지정이던 연락처는
    # 이름순 첫 매장만 남고 나머지는 **사라진다**(구조상 불가피, 되돌리면 정보 손실).
    op.execute(
        sa.text(
            """
            UPDATE contacts c
               SET store_id = pick.store_id
              FROM (
                    SELECT DISTINCT ON (cs.contact_id) cs.contact_id, cs.store_id
                      FROM contact_stores cs
                      JOIN stores s ON s.id = cs.store_id
                     ORDER BY cs.contact_id, s.name
                   ) AS pick
             WHERE c.id = pick.contact_id
            """
        )
    )
    op.drop_index('ix_contacts_org_visibility', table_name='contacts')
    op.create_index('ix_contacts_org_store', 'contacts', ['organization_id', 'store_id'], unique=False)
    op.drop_column('contacts', 'visibility')
    op.drop_index('ix_contact_stores_store', table_name='contact_stores')
    op.drop_table('contact_stores')
    # ### end Alembic commands ###
